import nodemailer, { Transporter, SentMessageInfo } from 'nodemailer';
import { EmailConfig } from '../data/testData';

export class EmailHelper {
  private transporter: Transporter;
  private config: EmailConfig;

  constructor(config: EmailConfig) {
    this.config = config;
    this.transporter = nodemailer.createTransport({
      host: config.host,
      port: config.port,
      secure: config.secure,
      auth: {
        user: config.user,
        pass: config.pass,
      },
    });
  }

  async sendEmail(subject: string, responseText: string, question: string = ''): Promise<SentMessageInfo> {
    const mailOptions = {
      from: this.config.from,
      to: this.config.to,
      subject,
      html: this.buildEmailBody(responseText, question),
    };

    const info: SentMessageInfo = await this.transporter.sendMail(mailOptions);
    console.log(`Email sent successfully. Message ID: ${info.messageId}`);
    return info;
  }

  async verifyConnection(): Promise<void> {
    await this.transporter.verify();
    console.log('SMTP connection verified successfully.');
  }

  private buildEmailBody(responseText: string, question: string): string {
    return `
      <html>
        <body style="font-family: Arial, sans-serif; padding: 20px; color: #333;">
          <h2 style="color: #10a37f;">ChatGPT Response</h2>
          <hr/>

          <p><strong>Question Asked (via Mic):</strong></p>
          <p style="background:#f5f5f5; padding:12px; border-radius:6px; border-left:4px solid #10a37f;">
            ${question}
          </p>

          <p><strong>ChatGPT Response:</strong></p>
          <p style="background:#f0f9f6; padding:12px; border-radius:6px;
                     white-space:pre-wrap; border-left:4px solid #10a37f;">
            ${responseText}
          </p>

          <hr/>
          <p style="color:#999; font-size:12px;">
            Generated by Playwright Automation &nbsp;|&nbsp; ${new Date().toLocaleString()}
          </p>
        </body>
      </html>
    `;
  }
}
